# Blog settings
title: Jake Lee
email: blog@jakelee.co.uk
description: Hello! These are all my non-programming posts, maybe a bit of gaming, maybe a bit of data analysis, maybe a bit of finance, who knows!
baseurl: ""
url: "https://jakelee.co.uk"
permalink: /:title/
show_excerpts: true
timezone: Europe/London

# Theme settings
theme: minima
paginate: 10
paginate_path: page/:num/
twitter_username: JakeLeeUK
github_username: JakeSteam
linkedin_username: Jake-Lee
stackoverflow_username: Jake-Lee
stackoverflow_id: 608312
giscus_repo: JakeSteam/blog-personal
giscus_repo_id: R_kgDOG3ebnw
giscus_category: Comments
giscus_category_id: DIC_kwDOG3ebn84CQ06P
rss: RSS

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Syntax highlighter settings
kramdown:
  syntax_highlighter_opts:
    default_lang: kotlin
    guess_lang: true

# Analytics settings
google_analytics: UA-220119060-2

